sudo: required

env:
  global:
     - CURRENT=$(pwd)
     - DOCKER_REPOSITORY=bwnyasse/md2codelab

services:
  - docker

stages:
  - name: compil
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master


jobs:
  include:
    - stage: compil
      script: bash $CURRENT/.docker/compil.sh
    - stage: build
      script: bash $CURRENT/.docker/build.sh
    - stage: deploy
      script: bash $CURRENT/.docker/deploy.sh
    



