sudo: required

env:
  global:
     - CURRENT=$(pwd)
     - DOCKER_REPOSITORY=bwnyasse/md2codelab

services:
  - docker

before_install:
  # Check current docker engine version
  - docker --version

  # set env vars in the build settings to interact with repositories
  # see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - echo "Testing Docker Hub credentials"
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD

before_install:
  - bash $CURRENT/.jobs/compil-in-docker.sh

install:
  - bash $CURRENT/.docker/dockerbuild.sh

deploy:

    # Deploy to docker hub
    provider: script
    script: bash $CURRENT/.docker/dockerhub.sh
    skip_cleanup: true
    on:
      branch: master