# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:

  mdBuilder:
    import: "package:md2codelab/builder.dart"
    builder_factories: ["mdBuilder"]
    build_extensions: {".md": [".md.html"]}
    build_to: source
    auto_apply: root_package