name: md2codelab
description: A simple tool to convert .md to google codelabA sample command-line application.
version: 0.0.1
author: bwnyasse

environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dependencies:
  markdown: "^2.0.0"
  html: any
  intl: "^0.15.6"
  resource: "^2.1.2"
  quiver: "^0.29.0+1"
  args: "^1.4.3"
  yaml: "^2.1.14"

dev_dependencies:
  build_runner: ^0.8.7
  build_test: ^0.10.0
  test: "^0.12.37"
