name: md2codelab
description: A simple tool to convert .md to google codelabA sample command-line application.
version: 0.0.1
author: bwnyasse

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  markdown: ^2.0.0
  html: any
  intl: ^0.15.6
  resource: ^2.1.2
  quiver: ^0.29.0+1
  args: ^1.4.3
  yaml: ^2.1.14
  build: ^1.1.4
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^0.4.0

dev_dependencies:
  build_runner: ^1.5.0
  build_test: ^0.10.7+3
  test: ^1.6.3
