categories: # Categories label
    1: process
    2: factory
    3: database
    4: web

categories_colors: # colors in Hex
    1: 1A73E8
    2: 02569B
    3: 71B958
    4: E37400

categories_icons: # Icons must be in icons/
    1: process.svg
    2: factory.svg
    3: database.svg
    4: web.svg


global:
  location: http://meteo.mipih.net/codelabs/
  name: Codelabs
  welcome: Codelabs @ Diff Tech Prodige !
  description: >
    "Cette IHM fournit une prise en main sous forme de codelabs tutorial. Ci-dessous la liste des codelabs
    disponibles."
  author: Team Diff Technique
  start_button: Démarrer



