name: md2codelab_ui
description: UI
version: 0.0.1
author: bwnyasse

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  angular: ^5.1.0
  #angular_components: ^0.14.0-alpha
  js: ^0.6.0
  yaml: ^2.1.14
  quiver: ^2.0.0
  ng_bootstrap: ^1.1.1
  
dev_dependencies:
  angular_test: ^2.0.0-alpha+9
  build_runner: ^1.5.0
  build_test: ^0.10.0
  build_web_compilers: ^2.1.0
  test: ^1.6.0
  sass: ^1.20.3
  build_daemon: ^1.0.0
